import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import type { JsonValue } from "../core/protocol";
import { ARTIFACT_KINDS, assertKind, type ArtifactRef } from "../domain/types";
import { DomainWorkspace } from "../domain/workspace";
import { ToolRegistry, type ToolDefinition } from "./registry";
import { validateDomainArtifact } from "./validation-domain";

export interface DomainToolOptions { repositoryRoot: string; workspace: DomainWorkspace; contracts?: Readonly<Record<string, string>> }
export function createDomainToolRegistry(options: DomainToolOptions): ToolRegistry { return new ToolRegistry(domainToolDefinitions(options)); }
export function domainToolDefinitions(options: DomainToolOptions): readonly ToolDefinition[] {
  const contracts = options.contracts ?? {};
  const definitions: ToolDefinition[] = [
    { name: "read_source", description: "Read a bounded slice of the frozen source document", inputSchema: objectSchema({ offset: { type: "integer", minimum: 0 }, length: { type: "integer", minimum: 1, maximum: 262144 } }), execute: async (raw) => { const item = record(raw), text = await options.workspace.readSource(), offset = item.offset === undefined ? 0 : integer(item.offset, "offset"), length = item.length === undefined ? Math.min(262144, text.length - offset) : integer(item.length, "length"); if (offset > text.length || length > 262144) throw new Error("source_range_invalid"); return { text: text.slice(offset, offset + length), offset, complete: offset + length >= text.length, sha256: options.workspace.ref.sourceSha256 }; } },
    { name: "read_contract", description: "Read one allow-listed repository contract", inputSchema: objectSchema({ name: { type: "string", minLength: 1, maxLength: 80 } }, ["name"]), execute: async (raw) => { const name = field(raw, "name"); const relative = contracts[name]; if (!relative) throw new Error("contract_not_allowed"); const file = safeRepositoryPath(options.repositoryRoot, relative); const text = await readFile(file, "utf8"); return { name, text, sha256: createHash("sha256").update(text).digest("hex") }; } },
    { name: "read_artifact", description: "Read one current artifact in this run", inputSchema: kindSchema(), execute: async (raw) => options.workspace.readCurrent(field(raw, "kind")) },
    { name: "validate_artifact", description: "Run the existing validator for a candidate", inputSchema: objectSchema({ kind: enumSchema(), value: {} }, ["kind", "value"]), execute: async (raw) => { const item = record(raw); const kind = field(raw, "kind"); assertKind(kind); return validateDomainArtifact(options.repositoryRoot, options.workspace, kind, item.value as JsonValue); } },
    { name: "write_artifact", description: "Commit a versioned JSON artifact in this run", inputSchema: objectSchema({ kind: enumSchema(), value: {}, dependencies: { type: "array", items: { type: "object" } }, readSet: { type: "array", items: { type: "string", maxLength: 256 } } }, ["kind", "value"]), execute: async (raw) => { const item = record(raw); const kind = field(raw, "kind"); assertKind(kind); const dependencies = parseDependencies(item.dependencies); const readSet = Array.isArray(item.readSet) ? item.readSet.map((entry) => { if (typeof entry !== "string") throw new Error("invalid_read_set"); return entry; }) : []; try { safeguard(kind, item.value); const verdict = await validateDomainArtifact(options.repositoryRoot, options.workspace, kind, item.value as JsonValue); if (hasHardFailure(verdict)) { await options.workspace.reject(kind, item.value, dependencies, readSet, verdict); throw new Error("artifact_validation_failed"); } return options.workspace.submit(kind, item.value, dependencies, readSet, verdict); } catch (error) { if (error instanceof Error && ["artifact_validation_failed", "stale_dependency"].includes(error.message)) throw error; await options.workspace.reject(kind, item.value, dependencies, readSet, { status: "rejected", errors: [error instanceof Error ? error.message : "rejected"] }); throw error; } } }
  ];
  return definitions.map((definition) => ({ ...definition, authorize: async (argumentsValue, context) => context.runState.runId === options.workspace.ref.runId && await (definition.authorize?.(argumentsValue, context) ?? true) }));
}
function safeguard(kind: string, value: unknown): void { if (kind !== "design-review") return; const item = record(value); const decisions = item.decisions; if (!Array.isArray(decisions)) throw new Error("invalid_design_review"); for (const decision of decisions) { const row = record(decision); if (row.status !== "pending") throw new Error("human_approval_forbidden"); } if (JSON.stringify(value).includes("source-verified")) throw new Error("source_verified_forbidden"); }
function hasHardFailure(verdict: JsonValue): boolean { const item = typeof verdict === "object" && verdict !== null && !Array.isArray(verdict) ? verdict as Record<string, JsonValue> : {}; return (Array.isArray(item.errors) && item.errors.length > 0) || (Array.isArray(item.hard) && item.hard.length > 0) || item.status === "FAIL"; }
function parseDependencies(value: unknown): ArtifactRef[] { if (value === undefined) return []; if (!Array.isArray(value)) throw new Error("invalid_dependencies"); return value.map((entry) => { const item = record(entry); const kind = field(item, "kind"); assertKind(kind); if (!Number.isInteger(item.version) || (item.version as number) < 1 || typeof item.sha256 !== "string" || !/^[a-f0-9]{64}$/.test(item.sha256)) throw new Error("invalid_dependency"); return { kind, version: item.version as number, sha256: item.sha256 }; }); }
function safeRepositoryPath(root: string, relative: string): string { if (path.isAbsolute(relative)) throw new Error("contract_path_escape"); const file = path.resolve(root, relative); if (!file.startsWith(path.resolve(root) + path.sep)) throw new Error("contract_path_escape"); return file; }
function record(value: unknown): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error("invalid_tool_arguments"); return value as Record<string, unknown>; }
function field(value: unknown, name: string): string { const result = record(value)[name]; if (typeof result !== "string") throw new Error(`invalid_${name}`); return result; }
function integer(value: unknown, name: string): number { if (!Number.isInteger(value) || (value as number) < 0) throw new Error(`invalid_${name}`); return value as number; }
const enumSchema = () => ({ type: "string" as const, enum: [...ARTIFACT_KINDS] });
const kindSchema = () => objectSchema({ kind: enumSchema() }, ["kind"]);
function objectSchema(properties: Record<string, object>, required: string[] = []): { type: "object"; properties: Record<string, object>; required: string[]; additionalProperties: false } { return { type: "object", properties, required, additionalProperties: false }; }
